http://checkman.io/blog/creating-a-javascript-library/
https://code.tutsplus.com/tutorials/build-your-first-javascript-library--net-26796
https://www.sitepoint.com/design-and-build-your-own-javascript-library/
https://www.codementor.io/chimeremezeukah/build-a-reusable-javascript-library-du1086d7l
https://ourcodeworld.com/articles/read/37/how-to-create-your-own-javascript-library
http://www.mikedoesweb.com/2012/creating-your-own-javascript-library/
https://www.lynda.com/JavaScript-tutorials/Creating-Open-Source-JavaScript-Library/604269-2.html
https://github.com/volojs/volo/wiki/Library-best-practices
http://www.adequatelygood.com/JavaScript-Module-Pattern-In-Depth.html
https://webstandardssherpa.com/reviews/secrets-of-awesome-javascript-api-design.html
https://code.tutsplus.com/articles/rolling-your-own-framework--cms-21810
https://s3.amazonaws.com/dailyjs/files/build-a-javascript-framework.pdf
